FROM python:3.9.5-slim-buster

ARG UID
ARG GID

WORKDIR /backend
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /backend/requirements.txt
COPY ./requirements-dev.txt /backend/requirements-dev.txt

RUN --mount=type=cache,target=/root/.cache/pip \
  apt-get update \
  && BUILD_DEPS='libpq-dev libffi-dev musl-dev gcc' \
  && DEBIAN_FRONTEND=noninteractive \
  && apt-get install -y netcat ${BUILD_DEPS} \
  && apt-get clean \
  && pip install --upgrade pip \
  && pip install pip-tools \
  && pip-sync requirements.txt requirements-dev.txt \
  && apt-get autoremove -y ${BUILD_DEPS} \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists /tmp/* /var/tmp/*

RUN groupadd -g $GID rootless
RUN useradd -m rootless -u $UID -g $GID
RUN mkdir -p /backend/logs

RUN chown -R $UID:$GID /backend
RUN chmod -R 775 /backend


USER rootless
