# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfidf/v1/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tfidf/v1/service.proto\x12\x05tfidf\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cPredictReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0e\n\x0cTrainRequest\"\x1d\n\nTrainReply\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\nMovieGenre\x12\x37\n\x07Predict\x12\x15.tfidf.PredictRequest\x1a\x13.tfidf.PredictReply\"\x00\x12\x31\n\x05Train\x12\x13.tfidf.TrainRequest\x1a\x11.tfidf.TrainReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tfidf.v1.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTREQUEST._serialized_start=33
  _PREDICTREQUEST._serialized_end=63
  _PREDICTREPLY._serialized_start=65
  _PREDICTREPLY._serialized_end=96
  _TRAINREQUEST._serialized_start=98
  _TRAINREQUEST._serialized_end=112
  _TRAINREPLY._serialized_start=114
  _TRAINREPLY._serialized_end=143
  _MOVIEGENRE._serialized_start=145
  _MOVIEGENRE._serialized_end=265
# @@protoc_insertion_point(module_scope)
