"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class PredictRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYNOPSIS_FIELD_NUMBER: builtins.int
    synopsis: builtins.str
    def __init__(
        self,
        *,
        synopsis: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["synopsis", b"synopsis"]) -> None: ...

global___PredictRequest = PredictRequest

class PredictReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PREDICTIONS_FIELD_NUMBER: builtins.int
    @property
    def predictions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Prediction]: ...
    def __init__(
        self,
        *,
        predictions: collections.abc.Iterable[global___Prediction] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["predictions", b"predictions"]) -> None: ...

global___PredictReply = PredictReply

class Prediction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GENRE_FIELD_NUMBER: builtins.int
    genre: builtins.str
    def __init__(
        self,
        *,
        genre: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["genre", b"genre"]) -> None: ...

global___Prediction = Prediction

class TrainRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___TrainRequest = TrainRequest

class TrainReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

global___TrainReply = TrainReply
