# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfidf/v1/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tfidf/v1/service.proto\x12\x05tfidf\"\"\n\x0ePredictRequest\x12\x10\n\x08synopsis\x18\x01 \x01(\t\"6\n\x0cPredictReply\x12&\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x11.tfidf.Prediction\"\x1b\n\nPrediction\x12\r\n\x05genre\x18\x01 \x01(\t\"\x0e\n\x0cTrainRequest\"\x1d\n\nTrainReply\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\nMovieGenre\x12\x37\n\x07Predict\x12\x15.tfidf.PredictRequest\x1a\x13.tfidf.PredictReply\"\x00\x12\x31\n\x05Train\x12\x13.tfidf.TrainRequest\x1a\x11.tfidf.TrainReply\"\x00\x62\x06proto3')



_PREDICTREQUEST = DESCRIPTOR.message_types_by_name['PredictRequest']
_PREDICTREPLY = DESCRIPTOR.message_types_by_name['PredictReply']
_PREDICTION = DESCRIPTOR.message_types_by_name['Prediction']
_TRAINREQUEST = DESCRIPTOR.message_types_by_name['TrainRequest']
_TRAINREPLY = DESCRIPTOR.message_types_by_name['TrainReply']
PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'tfidf.v1.service_pb2'
  # @@protoc_insertion_point(class_scope:tfidf.PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)

PredictReply = _reflection.GeneratedProtocolMessageType('PredictReply', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREPLY,
  '__module__' : 'tfidf.v1.service_pb2'
  # @@protoc_insertion_point(class_scope:tfidf.PredictReply)
  })
_sym_db.RegisterMessage(PredictReply)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'tfidf.v1.service_pb2'
  # @@protoc_insertion_point(class_scope:tfidf.Prediction)
  })
_sym_db.RegisterMessage(Prediction)

TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREQUEST,
  '__module__' : 'tfidf.v1.service_pb2'
  # @@protoc_insertion_point(class_scope:tfidf.TrainRequest)
  })
_sym_db.RegisterMessage(TrainRequest)

TrainReply = _reflection.GeneratedProtocolMessageType('TrainReply', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREPLY,
  '__module__' : 'tfidf.v1.service_pb2'
  # @@protoc_insertion_point(class_scope:tfidf.TrainReply)
  })
_sym_db.RegisterMessage(TrainReply)

_MOVIEGENRE = DESCRIPTOR.services_by_name['MovieGenre']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTREQUEST._serialized_start=33
  _PREDICTREQUEST._serialized_end=67
  _PREDICTREPLY._serialized_start=69
  _PREDICTREPLY._serialized_end=123
  _PREDICTION._serialized_start=125
  _PREDICTION._serialized_end=152
  _TRAINREQUEST._serialized_start=154
  _TRAINREQUEST._serialized_end=168
  _TRAINREPLY._serialized_start=170
  _TRAINREPLY._serialized_end=199
  _MOVIEGENRE._serialized_start=201
  _MOVIEGENRE._serialized_end=321
# @@protoc_insertion_point(module_scope)
